image: rust:slim

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y
        libzmq3-dev
        pkg-config
        gcc
        g++

test:
  stage: test
  script:
    - cargo test -- --nocapture