image: rust:slim

stages:
  - test

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y
        libzmq3-dev
        pkg-config
        gcc
        g++
    - cargo test -- --nocapture