image: rust:slim

stages:
  - test

test:
  stage: test
  script:
    - export RUST_BACKTRACE=1
    # - export RUST_LOG=debug
    - apt-get update
    - apt-get install -y
      libzmq3-dev
      pkg-config
      libseccomp-dev
      llvm-dev
      libclang-dev
      clang
      gcc
      g++
    - cargo test --tests --no-fail-fast -- --test-threads=1
