image: rust:slim

stages:
  - test

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y
        libzmq3-dev
        pkg-config
        gcc
        g++
    - env RUST_BACKTRACE=1 cargo test --tests --no-fail-fast -- --test-threads=1