[package]
name = "ana"
description = "A judge in Rust"
version = "0.3.0"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2018"
publish = false

[dependencies]
libc = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
zmq = "0.8"

[profile.release]
panic = "abort"