[package]
name = "ana"
description = "A judge in Rust"
version = "0.5.0"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2018"

[features]
default = ["gcc", "gxx"]
gcc = []
gxx = []

[dependencies]
clap = "2.32"
libc = "*"
unshare = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3"
tokio = "0.1"
zmq = "0.9"

[dev-dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
