[package]
name = "ana"
version = "0.6.1"
description = "A judge in Rust"
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/hr567/Ana"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2018"

[dependencies]
clap = "2.*"
# fuse = "*"
libmount = "0.1"
log = "0.4"
nix = "0.13"
serde = "1.*"
serde_json = "1.*"
serde_derive = "1.*"
tempfile = "3.*"
tokio = "0.1"
tokio-threadpool = "0.1"
unshare = "0.5"
uuid = { version = "0.7", features = ["v4"] }
zmq = { version = "0.9", optional = true }

[dev-dependencies]
env_logger = "0.6.0"

[features]
default = ["gcc", "gxx", "zmq_mod"]

gcc = []
gxx = []
zmq_mod = ["zmq"]
