[package]
name = "ana"
description = "A judge in Rust"
version = "0.4.2"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2018"

[dependencies]
clap = "2.32"
futures = "0.1"
libc = "*"
unshare = "0.5"
uuid = { version = "0.7", features = ["serde", "v4"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-threadpool = "0.1"
zmq = "0.9"