[package]
name = "Ana"
description = "A judge in Rust"
version = "0.0.1"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2018"
publish = false

[dependencies]
cgroups = "0.0.2"
clap = "2.32"
rand = "0.5.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
zmq = {git = "https://gitlab.com/hr567/rust-zmq.git"}
