[package]
name = "ana"
version = "0.10.0-alpha"
description = "A judge in Rust"
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/hr567/Ana"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2018"
build = "build.rs"

[dependencies]
# futures = "0.3.1"  # Use futures-preview instead until futures in tonic is available
futures-preview = "0.3.0-alpha.19"
lazy_static = "1.3.0"
log = "0.4.8"
tokio = "0.2.0-alpha.6"

rand = "0.7.0"
nix = "0.15.0"
tempfile = "3.0.8"

# Command line interface
clap = { version = "2.33.0", features = ["suggestions", "color"] }

# Data serialization/deserialization
serde = { version = "1.0.92", features = ["derive"] }
bincode = "1.1.4"
toml = "0.5.5"

# RPC requirement
bytes = {version = "0.4", optional = true }
prost = {version = "0.5", optional = true }
tonic = { version = "0.1.0-alpha.6", optional = true }

[dev-dependencies]
lazy_static = "1.3.0"

serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"

[build-dependencies]
tonic-build = { version = "0.1.0-alpha.6", optional = true }

bincode = "1.1.4"
lazy_static = "1.3.0"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"

bindgen = { version = "0.52.0", optional = true }

[features]
default = ["rpc"]
rpc = ["tonic", "bytes", "prost", "tonic-build"]

[badges]
gitlab = { repository = "https://gitlab.com/hr567/liboj", branch = "master" }
